# Generated by Django 4.2.8 on 2023-12-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professional_Training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_training',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='professional_training',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
