# Generated by Django 4.2.8 on 2024-01-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional_Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=200, null=True, verbose_name='Título')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitulo', models.CharField(default='', max_length=200, null=True, verbose_name='Subtítulo')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitle')),
                ('contenido', models.TextField(default='', null=True, verbose_name='Contenido')),
                ('content', models.TextField(verbose_name='Content')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('image', models.ImageField(upload_to='professional_studies', verbose_name='Imagen')),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Nivel')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'professional_studies',
                'verbose_name_plural': 'professional_studies',
                'ordering': ['-created'],
            },
        ),
    ]
