# Generated by Django 4.2.8 on 2024-01-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professional_Studies', '0002_remove_professional_studies_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional_studies',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
